import type { Playlist, PlaylistTrack } from "@nestify/shared";

// ツリー構造のモックデータ（Nestify デモ用）
// ルートプレイリスト 3 件 + ネスト 2 件 + トラック 5 件

const MOCK_USER_ID = "00000000-0000-0000-0000-000000000001";

export const MOCK_USER = {
  id: MOCK_USER_ID,
  spotifyId: "mock_user",
  displayName: "Mock User",
  email: "mock@example.com",
  imageUrl: null,
  accessToken: "mock_access_token",
  refreshToken: "mock_refresh_token",
  tokenExpiresAt: new Date(Date.now() + 3600 * 1000).toISOString(),
  createdAt: new Date().toISOString(),
};

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: "pl-001",
    userId: MOCK_USER_ID,
    name: "All Music",
    icon: "🎵",
    color: "linear-gradient(135deg,#7c6af7,#f76a8a)",
    parentId: null,
    order: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    children: [
      {
        id: "pl-002",
        userId: MOCK_USER_ID,
        name: "Lo-fi Beats",
        icon: "☕",
        color: "linear-gradient(135deg,#6af7c8,#7c6af7)",
        parentId: "pl-001",
        order: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        children: [
          {
            id: "pl-004",
            userId: MOCK_USER_ID,
            name: "Morning Lo-fi",
            icon: "🌅",
            color: "linear-gradient(135deg,#f7e26a,#6af7c8)",
            parentId: "pl-002",
            order: 0,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "pl-003",
        userId: MOCK_USER_ID,
        name: "Chill Vibes",
        icon: "🌙",
        color: "linear-gradient(135deg,#f76a8a,#6af7c8)",
        parentId: "pl-001",
        order: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "pl-005",
    userId: MOCK_USER_ID,
    name: "Workout",
    icon: "💪",
    color: "linear-gradient(135deg,#f76a8a,#f7a26a)",
    parentId: null,
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// フラット版（検索・更新用）
export const MOCK_PLAYLISTS_FLAT: Playlist[] = [
  {
    id: "pl-001",
    userId: MOCK_USER_ID,
    name: "All Music",
    icon: "🎵",
    color: "linear-gradient(135deg,#7c6af7,#f76a8a)",
    parentId: null,
    order: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "pl-002",
    userId: MOCK_USER_ID,
    name: "Lo-fi Beats",
    icon: "☕",
    color: "linear-gradient(135deg,#6af7c8,#7c6af7)",
    parentId: "pl-001",
    order: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "pl-003",
    userId: MOCK_USER_ID,
    name: "Chill Vibes",
    icon: "🌙",
    color: "linear-gradient(135deg,#f76a8a,#6af7c8)",
    parentId: "pl-001",
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "pl-004",
    userId: MOCK_USER_ID,
    name: "Morning Lo-fi",
    icon: "🌅",
    color: "linear-gradient(135deg,#f7e26a,#6af7c8)",
    parentId: "pl-002",
    order: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "pl-005",
    userId: MOCK_USER_ID,
    name: "Workout",
    icon: "💪",
    color: "linear-gradient(135deg,#f76a8a,#f7a26a)",
    parentId: null,
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_TRACKS: PlaylistTrack[] = [
  {
    id: "track-001",
    playlistId: "pl-002",
    spotifyTrackId: "spotify:track:001",
    order: 0,
    addedAt: new Date().toISOString(),
    track: {
      id: "001",
      name: "Rainy Day",
      artists: ["ChillHop Music"],
      album: "Lo-fi Collection",
      durationMs: 180000,
      previewUrl: null,
      imageUrl: null,
    },
  },
  {
    id: "track-002",
    playlistId: "pl-002",
    spotifyTrackId: "spotify:track:002",
    order: 1,
    addedAt: new Date().toISOString(),
    track: {
      id: "002",
      name: "Coffee Break",
      artists: ["Lofi Girl"],
      album: "Beats to Study",
      durationMs: 210000,
      previewUrl: null,
      imageUrl: null,
    },
  },
  {
    id: "track-003",
    playlistId: "pl-004",
    spotifyTrackId: "spotify:track:003",
    order: 0,
    addedAt: new Date().toISOString(),
    track: {
      id: "003",
      name: "Morning Dew",
      artists: ["Ambience"],
      album: "Morning Sessions",
      durationMs: 195000,
      previewUrl: null,
      imageUrl: null,
    },
  },
  {
    id: "track-004",
    playlistId: "pl-003",
    spotifyTrackId: "spotify:track:004",
    order: 0,
    addedAt: new Date().toISOString(),
    track: {
      id: "004",
      name: "Midnight Blue",
      artists: ["NightOwl"],
      album: "Chill Sessions",
      durationMs: 225000,
      previewUrl: null,
      imageUrl: null,
    },
  },
  {
    id: "track-005",
    playlistId: "pl-005",
    spotifyTrackId: "spotify:track:005",
    order: 0,
    addedAt: new Date().toISOString(),
    track: {
      id: "005",
      name: "Power Up",
      artists: ["BeatMaster"],
      album: "Workout Hits",
      durationMs: 240000,
      previewUrl: null,
      imageUrl: null,
    },
  },
];
